CREATE TABLE TAXI(
    ID INT NOT NULL AUTO_INCREMENT,
    KUNDE INT NOT NULL,
    FIRMA INT NOT NULL,
    AUSADRESSE VARCHAR(150) NOT NULL,
    AUSGPS VARCHAR(100) NOT NULL,
    BISADRESSE VARCHAR(150) NOT NULL,
    BISGPS VARCHAR(100) NOT NULL, 
    AUSDATUM DATETIME DEFAULT CURRENT_TIMESTAMP, 
    BISDATUM DATETIME DEFAULT CUTTENT_TIMESTAMP,
    PREIS DECIMAL(10,2) DEFAULT 0,
    PRIMARY KEY(ID)
);
